name: Cypress Tests
on: [push]
  
jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.16.0-chrome105-ff104-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          runTests: false
          
  assessment-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-16.18.1-chrome-110.0.5481.96-1-ff-109.0-edge-110.0.1587.41-1
      options: --user 1001
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress info
        run: npx cypress info

      - name: Node info
        run: node -v

      - name: "Tests - Assessment - Chrome"
        id: cypress
        uses: cypress-io/github-action@v5
        with:
          start: npx cypress run
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          headed: true
          record: true
          group: "Assessment"
          spec: cypress/e2e/cypress-web-assessment/*
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: "cypress:server:args"

      - name: Handle ECONNREFUSED error
        if: ${{ failure() }}
        run: |
          echo "Cypress step failed. Checking for known ECONNREFUSED issue."
          exit_code=${{ needs.assessment-tests.outputs.exit_code }}
          if [ "$exit_code" = "connect ECONNREFUSED 127.0.0.1:3000" ]; then
            echo "Cypress step failed with ECONNREFUSED. Passing despite the error."
            exit 0
          else
            echo "Cypress step failed with exit code $exit_code. Check for other errors."
            exit 1
          fi
